## Numpy-2 : Data-Types in Numpy Arrays

**Installing Numpy**

In [18]:
!pip install numpy

**Importing numpy**

In [2]:
# np is just an alias (a nickname) for the numpy module.
import numpy as np

**Checking Numpy Version**

In [3]:
np.__version__

'2.3.0'

**Numpy 1D, 2D and 3D Array**

In [4]:
# a list of numbers will create a 1D array => Think of this as a single row or a single column of values.
a1D = np.array([1, 2, 3, 4])
a1D

array([1, 2, 3, 4])

In [5]:
print(type(a1D))

<class 'numpy.ndarray'>


In [6]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, 

In [7]:
print(f"shape is {a1D.shape} and size is {a1D.size}")

shape is (4,) and size is 4


In [195]:
# a list of lists will create a 2D array => A matrix: rows and columns.
a2D = np.array([[1, 2], [3, 4]])
a2D

array([[1, 2],
       [3, 4]])

In [196]:
print(f"shape is {a2D.shape} and size is {a2D.size}")

shape is (2, 2) and size is 4


In [9]:
# An array of matrices.
# further nested lists will create higher-dimensional arrays. In general, any array object is called an ndarray in NumPy
a3D_list = [
    [
        [1,2],[3,4]
    ], [
        [5,6],[7,8]
    ]
] 
type(a3D_list)

list

In [10]:
a3D = np.array(a3D_list)
a3D

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [197]:
print(f"shape is {a3D.shape} and size is {a3D.size}")

shape is (2, 2, 2) and size is 8


**Supported data types in numpy**

In [ ]:
# NumPy arrays (ndarray) are homogeneous, meaning all elements must be of the same data type.

In [198]:
np.array([1, 2, 3], dtype=np.int32)

array([1, 2, 3], dtype=int32)

In [199]:
np.array([1.5, 2.7], dtype=np.float64)

array([1.5, 2.7])

In [206]:
np.array([1, 2.7]) # NumPy automatically upcasts them to the most compatible common type.

array([1. , 2.7])

In [208]:
np.array([True, False, True], dtype=bool)

array([ True, False,  True])

In [213]:
np.array(['apple', 'banana'], dtype='U10') # Little endian byte order - Unicode strings, each up to 10 characters long

array(['apple', 'banana'], dtype='<U10')

In [166]:
np.array(['2023-01-01', '2023-02-01'], dtype='datetime64[D]')

array(['2023-01-01', '2023-02-01'], dtype='datetime64[D]')

In [11]:
np.array([1, 'b', 3])

array(['1', 'b', '3'], dtype='<U21')

In [12]:
np.array([1, '2', 3], dtype=np.int32)

array([1, 2, 3], dtype=int32)

In [13]:
np.array([1, 'b', 3], dtype=np.int32)

ValueError: invalid literal for int() with base 10: 'b'

**record array or structured array**

- Structured arrays in NumPy are homogeneous at the array level (each element has the same layout).
- We can specify a type and, optionally, a name on a per-column basis. This makes sorting and filtering even more powerful, and it can feel similar to working with data in Excel, CSVs, or relational databases.

In [ ]:
# Record arrays (also called structured arrays) in NumPy are indeed implemented similar to struct in C.

In [15]:
data = np.array([ ("aman", 22, 90),
                 ("ankit", 15, 60), 
                 ("akash", 18, 90), 
                 ("aditya", 22, 80)], 
                dtype=[("name", 'U15' ), ("age", np.int32), ("marks", int),]
               )

In [16]:
data

array([('aman', 22, 90), ('ankit', 15, 60), ('akash', 18, 90),
       ('aditya', 22, 80)],
      dtype=[('name', '<U15'), ('age', '<i4'), ('marks', '<i8')])

**You can specify the dtype (data type) in several equivalent ways.**
1. Using NumPy type strings (compact format) - `[("name", "U15"), ("age", "i4"), ("marks", "i4")]`
2. Using NumPy type objects (recommended) - `[("name", np.unicode_), ("age", np.int32), ("marks", np.int32)]`
3. Mixing Python built-in types and NumPy types - `[("name", str), ("age", int), ("marks", np.int32)]`

In [17]:
print(data[0])

('aman', 22, 90)


In [18]:
data["name"]

array(['aman', 'ankit', 'akash', 'aditya'], dtype='<U15')

### By default, NumPy arrays (ndarray) are homogeneous, meaning all elements must be of the same data type.

- **Homogeneous arrays allow:**
  1. Vectorized operations  
  2. Efficient memory layout (contiguous blocks)  
  3. Fast computations using C under the hood  

- **NumPy** is designed for arrays of fixed-size elements — typically numerical data types (integers, floats), but also supports strings, booleans, dates, and custom structured types.

- All elements in a **NumPy array** share the same data type (`dtype`).

- The data is stored in a **contiguous block of memory** for efficiency.


It can support heterogeneous types using object arrays or structured dtypes, but these lose most performance benefits.

In [26]:
het = np.array([1, 'b', 3, True, 6.5])
het

array(['1', 'b', '3', 'True', '6.5'], dtype='<U32')

In [27]:
het.dtype # Little endian byte order - Unicode strings, each up to 21 characters long

dtype('<U32')

In [28]:
print(type(het[0]))

<class 'numpy.str_'>


In [29]:
# NumPy treats this as an array of generic Python objects.
# You lose all vectorized speed benefits of NumPy.
# Operations like +, broadcasting, etc., don't work efficiently.
het = np.array([1, 'b', 3, True, 6.5], dtype=object)
het

array([1, 'b', 3, True, 6.5], dtype=object)

In [30]:
het.dtype

dtype('O')

In [31]:
print(type(het[0]))

<class 'int'>
